query MediaUploadSignature($ownerType: MediaOwnerTypeEnum!, $kind: MediaKindEnum!, $ownerId: Int) {
  mediaUploadSignature(ownerType: $ownerType, kind: $kind, ownerId: $ownerId) {
    data {
      signature
      timestamp
      apiKey
      cloudName
      folder
    }
  }
}

mutation AttachMedia($input: InputAttachMedia!) {
  attachMedia(input: $input) {
    message
    data {
      id
      kind
      url
    }
  }
}

mutation RemoveMedia($mediaId: Int!) {
  removeMedia(mediaId: $mediaId) {
    message
  }
}
