query MyReviews($first: Int, $after: String) {
  myReviews(first: $first, after: $after) {
    data {
      id
      review
      rating
      createdAt
      helpfulCount
      photoCount
      place {
        id
        label
        address
        priceRange
        averageRating
        reviewCount
        isVerified
        openNow
        trendingScore
        coverPhotoUrl
        profilePicture
        savedByMe
        savedListType
        category {
          label
          icon
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
