query MyNotifications($filter: NotificationFilterEnum) {
  myNotifications(filter: $filter) {
    data {
      id
      type
      message
      placeId
      place {
        id
        label
      }
      read
      createdAt
    }
  }
}

query UnreadNotificationCount {
  unreadNotificationCount
}

mutation MarkNotificationRead($notificationId: Int!) {
  markNotificationRead(notificationId: $notificationId) {
    message
  }
}

mutation MarkAllNotificationsRead {
  markAllNotificationsRead {
    message
  }
}

mutation DeleteNotification($notificationId: Int!) {
  deleteNotification(notificationId: $notificationId) {
    message
  }
}
