query ListPlaces($sort: PlaceSortEnum, $near: GeoInput, $filter: PlaceFilterInput, $first: Int, $after: String) {
  listPlaces(sort: $sort, near: $near, filter: $filter, first: $first, after: $after) {
    message
    data {
      id
      label
      address
      priceRange
      averageRating
      reviewCount
      isVerified
      trendingScore
      coverPhotoUrl
      latitude
      longitude
      distance
      openNow
      savedByMe
      savedListType
      category {
        id
        label
        icon
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
