export enum BadgeKeyEnum {
    FIRST_REVIEW = 'FIRST_REVIEW',
    PROLIFIC_REVIEWER = 'PROLIFIC_REVIEWER',
    HELPFUL_REVIEWER = 'HELPFUL_REVIEWER',
    EXPLORER = 'EXPLORER',
    ELITE_REVIEWER = 'ELITE_REVIEWER',
}
